#!/bin/bash

echo "🔧 Setting up Vercel environment variables for API..."
echo ""
echo "Run these commands to set your environment variables:"
echo ""
echo "cd /Users/charliebailey/Downloads/Landing-page---Think-ALM-main/api"
echo ""
echo "# Set each environment variable:"
echo "echo 'smtp.office365.com' | npx vercel env add EMAIL_HOST production"
echo "echo '587' | npx vercel env add EMAIL_PORT production"
echo "echo 'charlie@thinklm.ai' | npx vercel env add EMAIL_USER production"
echo "echo 'Thinkalm1993!' | npx vercel env add EMAIL_PASSWORD production"
echo "echo 'ThinkALM <charlie@thinklm.ai>' | npx vercel env add EMAIL_FROM production"
echo "echo 'charlie@thinklm.ai' | npx vercel env add ADMIN_EMAIL production"
echo "echo '/tmp/uploads' | npx vercel env add UPLOAD_DIR production"
echo "echo '52428800' | npx vercel env add MAX_FILE_SIZE production"
echo ""
echo "After setting variables, redeploy:"
echo "npx vercel --prod"
